/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./src/components/ui/Alert.vue')['default']
    AllBooksSearchBar: typeof import('./src/components/global/search-bar/AllBooksSearchBar.vue')['default']
    BookBookmarks: typeof import('./src/components/book/BookBookmarks.vue')['default']
    BookFontAndLayout: typeof import('./src/components/book/BookFontSizeSetter.vue')['default']
    BookFontFamilySetter: typeof import('./src/components/book/BookFontFamilySetter.vue')['default']
    BookFontSize: typeof import('./src/components/book/BookFontSizeSetter.vue')['default']
    BookFontSizeSetter: typeof import('./src/components/book/BookFontSizeSetter.vue')['default']
    BookFooter: typeof import('./src/components/book/BookFooter.vue')['default']
    BookInfo: typeof import('./src/components/book/BookInfo.vue')['default']
    BookLayoutSetter: typeof import('./src/components/book/BookLayoutSetter.vue')['default']
    BookListItem: typeof import('./src/components/home/BookListItem.vue')['default']
    BookSidebar: typeof import('./src/components/book/BookSidebar.vue')['default']
    BookTextSpacing: typeof import('./src/components/book/BookTextSpacing.vue')['default']
    BookTextSpacingSetter: typeof import('./src/components/book/BookTextSpacingSetter.vue')['default']
    BookToc: typeof import('./src/components/book/BookToc.vue')['default']
    Button: typeof import('./src/components/ui/Button.vue')['default']
    CurrentBookSearchBar: typeof import('./src/components/global/search-bar/CurrentBookSearchBar.vue')['default']
    ErrorAlert: typeof import('./src/components/global/ErrorAlert.vue')['default']
    Header: typeof import('./src/components/global/Header.vue')['default']
    Icon: typeof import('./src/components/ui/Icon.vue')['default']
    InputText: typeof import('./src/components/ui/InputText.vue')['default']
    Layout: typeof import('./src/components/global/Layout.vue')['default']
    Logo: typeof import('./src/components/global/Logo.vue')['default']
    Modal: typeof import('./src/components/ui/Modal.vue')['default']
    NavBar: typeof import('./src/components/global/NavBar.vue')['default']
    Overlay: typeof import('./src/components/ui/Overlay.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/global/search-bar/SearchBar.vue')['default']
    Select: typeof import('./src/components/ui/Select.vue')['default']
    Separator: typeof import('./src/components/ui/Separator.vue')['default']
    Slider: typeof import('./src/components/ui/Slider.vue')['default']
    Spinner: typeof import('./src/components/ui/Spinner.vue')['default']
    ThemeModal: typeof import('./src/components/global/ThemeModal.vue')['default']
    Toast: typeof import('./src/components/ui/Toast.vue')['default']
    Versions: typeof import('./src/components/Versions.vue')['default']
  }
}
